<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note [
<!ELEMENT note (head, mods, pros, cons)>
<!ELEMENT head (#PCDATA)>
<!ELEMENT mods (#PCDATA)>
<!ELEMENT pros (#PCDATA)>
<!ELEMENT cons (#PCDATA)>
<!ENTITY repeater "30-30 Repeater">
]>
<?xml-stylesheet type="text/css" href="styles.css"?>
<note>
<head>&repeater;</head>
<mods>Extended Heavy Mag
Sniper Stock
1x HCOG “Classic”
1x Holo
1x-2x Variable Holo
2x HCOG “Bruiser”
3x HCOG "Ranger"
2x-4x Variable AOG
Shatter Caps
Dual Shell</mods>
<pros>Strong medium-range potential.
Low recoil.
Decent fire rate.
Ability to reload bullets during a fight, one at a time, without emptying the mag.
Fairly reliable hipfire at close range, especially with the Shatter Caps Hop-Up.
Can open doors by shooting the handle.
Efficient with ammo</pros>
<cons>Aiming down sights required for charged shots, which reduces the fire rate.
Obstructive iron sights.
Rather slow reload speed (less than 3 bullets/second).
At close range, easily outclassed by shotguns and SMGs without the Shatter Caps Hop-Up.
Low DPS
At long range, the slow bullet traveling speed makes it harder to hit enemies.
Small mag size without an Extended Heavy Mag.</cons>
</note>